punk_social/accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from accounts import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

### Accounts URLs ###
# Password reset still in development 

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^signup/$', user_views.register, name='register'),
    url('^profile/(?P<slug>[-\w]+)/$', user_views.profile_view, name='profile_view'),
    url('^edit-profile/$', user_views.edit_profile, name='edit_profile'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    url(r'^password-reset/done/', auth_views.PasswordResetView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

punk_social/posts/urls.py
from django.conf.urls import url
from . import views

### Posts URLs ###

app_name = 'posts'

urlpatterns = [
    url(r'^new/$',views.CreatePost.as_view(template_name='post_form.html'),name='create'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.post_detail,name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(template_name='post_confirm_delete.html'),name='delete'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
]

punk_social/punk_social/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views
from accounts import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

punk_social/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from django.conf import settings
from autoslug import AutoSlugField

### Accounts models ###

# Profile model created upon base user registration
# Dependent on base user model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='images/punk.jpg', upload_to='profile_pics')
    slug = AutoSlugField(populate_from='user',unique=True)
    bio = models.CharField(max_length=255, blank=True)
    portfolio_site = models.URLField(blank=True)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return "/accounts/{}".format(self.slug)

def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Profile.objects.create(user=instance)
        except:
            pass

post_save.connect(post_save_user_model_receiver, sender=settings.AUTH_USER_MODEL)

punk_social/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

### Accounts forms ###

def validate_email(value):
    if User.objects.filter(email = value).exists():
        raise forms.ValidationError(
            ("An account exists with this email. Please enter a unique email."),
            params = {'value':value}
        )

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField(validators = [validate_email])

	class Meta:
		model = User
		fields = ['username','email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['bio', 'image', 'portfolio_site']

punk_social/accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404

from posts.models import Post, Like
from groups.models import Group
from .models import Profile
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import get_user_model
User = get_user_model()

### Accounts views ###

# p will represent the profile
# u will represent the user

# Profile view fetches user related model content from profile model using profile slug for ID
# View is based on profile slug NOT user
# If profile is for user, this is distinguished at template level
@login_required
def profile_view(request, slug):
	p = Profile.objects.filter(slug=slug).first()
	u = p.user
	user_posts = Post.objects.filter(user_id=u)
	user_groups = Group.objects.filter(members=u)

	context = {
		'u': u,
		'post_count': user_posts.count,
		'posts': user_posts,
		'groups': user_groups,
		}

	# Post likes still in development
	if request.user.is_authenticated:
		liked = [i for i in Post.objects.all() if Like.objects.filter(user = request.user, post=i)]
		context['liked_post'] = liked

	return render(request, "profile.html", context)

# Registration view creates user model instance
def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, 'Your account has been created! You can now login!')
			return redirect('accounts:login')
	else:
		form = UserRegisterForm()
	return render(request, 'register.html', {'form':form})

# Edit profile view shows user model and profile model info simultaneously
# This gives the user and profile models a uniform identity to the user
@login_required
def edit_profile(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, 'Your account has been updated!')
			return redirect('accounts:profile_view', slug=request.user.profile.slug)
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)
	context ={
		'u_form': u_form,
		'p_form': p_form,
	}
	return render(request, 'edit_profile.html', context)

punk_social/accounts/templates/edit_profile.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Profile update page -->
<div class="container filled">
  <div class="row">
    <div class="col-lg-12 mx-auto">
      <h5 class="text-center"><b>Update Profile</b></h5>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <br>
          <!-- User update and profile update forms -->
          {{ u_form|crispy }} {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
          <button
            class="btn btn-primary btn-block text-uppercase"
            type="submit"
          >
          Update</button>
          <br>
          <a
            class="btn btn-warning btn-block text-uppercase"
            href="#"
            >Go Back</a
            >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

punk_social/accounts/templates/login.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Login page -->
<div class="container filled">
  <h2 class="text-center"><b>Sign In</b></h2>
  <form method="POST">
    {% csrf_token %}
    <!-- Login form -->
    <fieldset class="form-group">
      <br />
      {{ form|crispy }}
    </fieldset>

    <div class="form-group">
      <div class="text-center">
        <button
          class="btn btn-block btn-primary text-uppercase"
          type="submit">
        Login
        </button>
        <br/>
        <a class="btn btn-block btn-sm btn-warning text-uppercase"
          href="{% url 'accounts:password_reset'%}">
        Forgot Password?
        </a>
      </div>
    </div>

    <small><p class="text-center">
      Not registered yet!
      <a href="{% url 'accounts:register' %}"><b>Register Now!</b></a>
    </p></small>
  </form>
</div>

{% endblock %}

punk_social/accounts/templates/logout.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Logout page -->
<!-- Not currently in use! -->
<div class="container" style="background-color:#ffffff">
  <h2 class="text-center"><b>Sign In</b></h2>
  <form class="form-signin" method="POST">
    {% csrf_token %}

    <fieldset class="form-group">
      <br>
      {{ form|crispy }}
    </fieldset>

    <div class="form-group">
      <div class="text-center">
        <button
          class="btn btn-block btn-primary text-uppercase"
          type="submit">
        Logout!
        </button>
      </div>
    </div>

    <small><p class="text-center">
      Nevermind! I'll
      <a href="{% url 'accounts:login' %}"><b>Login</b></a>
      or
      <a href="{% url 'accounts:register' %}"><b>Register!</b></a>
    </p></small>
  </form>
</div>

{% endblock %}

punk_social/accounts/templates/password_reset.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Password reset form -->
<!-- Not currently in use! -->
<!-- Password reset in development -->

<div class="container filled">
  <h2 class="text-center"><b>Sign In</b></h2>
  <form class="form-signin" method="POST">
    {% csrf_token %}

    <fieldset class="form-group">
      <br />
      {{ form|crispy }}
    </fieldset>

    <div class="form-group">
      <div class="text-center">
        <button
          class="btn btn-block btn-primary text-uppercase"
          type="submit">
        Reset Password
        </button>
      </div>
    </div>

    <small><p class="text-center">
      Nevermind! I'll
      <a href="{% url 'accounts:login' %}"><b>Login</b></a>
      or
      <a href="{% url 'accounts:register' %}"><b>Register!</b></a>
    </p></small>
  </form>
</div>

{% endblock %}

punk_social/accounts/templates/password_reset_complete.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Password reset complete -->
<!-- Not currently in use! -->
<!-- Password reset in development -->

<div class="container filled">
  <h2 class="text-center"><b>Password reset complete!</b></h2>
  <a href="{% url 'accounts:login' %}"><b>Login</b></a>
</div>

{% endblock %}

punk_social/accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Password reset confirm -->
<!-- Not currently in use! -->
<!-- Password reset in development -->

<div class="container filled">
  <h2 class="text-center"><b>Sign In</b></h2>
  <form class="form-signin" method="POST">
    {% csrf_token %}

    <fieldset class="form-group">
      <br />
      {{ form|crispy }}
    </fieldset>

    <div class="form-group">
      <div class="text-center">
        <button
          class="btn btn-block btn-primary text-uppercase"
          type="submit">
        Confirm Reset Password
        </button>
      </div>
    </div>

    <small><p class="text-center">
      Nevermind! I'll
      <a href="{% url 'accounts:login' %}"><b>Login</b></a>
      or
      <a href="{% url 'accounts:register' %}"><b>Register!</b></a>
    </p></small>
  </form>
</div>

{% endblock %}

punk_social/accounts/templates/password_reset_done.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Password reset sent -->
<!-- Not currently in use! -->
<!-- Password reset in development -->

<div class="container filled">
  <h2 class="text-center"><b>Password reset link sent!</b></h2>
  <p class="text-center"><b><a href="https://mail.google.com/mail/u/0/">Open Gmail</a></b></p>
</div>

{% endblock %}

punk_social/accounts/templates/profile.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}

{% block bodyblock %}
{% if user.is_authenticated %}

<!-- Profile page -->

<!-- Left column -->
<div class="col-md-4">

  <!-- Profile info -->
  <div class="content-block filled profile-info">
    <h3 class="text-center" style="margin-top:0px;">@{{u.username}}</h3>
    <!-- Here to check image URL -->
    <!-- <script type="text/javascript">
      document.write("{{u.profile.image.url}}");
    </script> -->
    <div class="text-center profile-image">
      <img
        src="{{u.profile.image.url}}" alt="PUNK"
        class="rounded"
        style="max-width:100%;"
      >
    </div>
    <p>Portfolio:  <a href="{{u.profile.portfolio_site}}">
      {{u.profile.portfolio_site}}</a></p>
    <p>Bio:  {{u.profile.bio}}</p>
    {% if request.user == u %}
    <div style="padding:10px">
      <a class="btn btn-info btn-block btn-sm" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
      <a class="btn btn-info btn-block btn-sm" href="{% url 'accounts:logout' %}">Log Out</a>
    </div>
    {% endif %}
  </div>
  <br><br>

  <!-- User Groups -->
  <div class="content-block filled user-groups">
    <h4 class="text-center" style="margin:5px">@{{u.username}}'s Groups:</h4>
    {% if request.user == u %}
      <br>
      <a href="{% url 'groups:create' %}" class="btn btn-sm btn-block btn-primary">
        <span class="glyphicon glyphicon-plus-sign"></span>
        Create New Group
      </a>
    {% endif %}
    <br>

    <!-- Created Groups -->
    <h5 class="text-center" style="margin:5px">Created groups:</h5>
    <!-- Loop all created groups from user model related_name -->
    {% if u.groups_created.count == 0 %}
      <div class="group-thumbnail">
        <p>No groups created yet!</p>
      </div>
      <br>
    {% else %}
      {% for group in u.groups_created.all %}
        <div class="group-thumbnail">
          <p>
            <a href="{% url 'groups:detail' slug=group.slug %}">{{group.name}}</a>
            <br>
            <strong>{{group.members.count}}</strong>
            Member{{group.members.count|pluralize}} |
            <strong>{{group.posts.count}}</strong>
            Post{{group.posts.count|pluralize}}
          </p>
        </div>
        <br>
      {% endfor %}
    {% endif %}

    <!-- Joined Groups -->
    <h5 class="text-center" style="margin:5px">Joined Groups:</h5>
    <!-- Loop all joined groups fed in from context dict -->
    {% if groups.count == 0 %}
      <div class="group-thumbnail">
        <p>No groups joined yet!</p>
      </div>
      <br>
    {% else %}
      {% for group in groups %}
      <div class="group-thumbnail">
        <p>
          <a href="{% url 'groups:detail' slug=group.slug %}">{{group.name}}</a>
          <br>
          <strong>{{group.members.count}}</strong>
          Member{{group.members.count|pluralize}} |
          <strong>{{group.posts.count}}</strong>
          Post{{group.posts.count|pluralize}}
        </p>
      </div>
      <br>
      {% endfor %}
    {% endif %}
  </div>

<br><br>
</div>


<!-- Right column -->
<!-- Post list -->
{% if user.is_authenticated %}
<div class="col-md-8 clear">
{% endif %}
  <h3 class="sans-font">User posts:</h3>
  <!-- Check if user has made any posts -->
  {% if u.posts.count == 0 %}
    <h3>No posts created yet!</h3>
  {% else %}
    <!-- Loop through user created posts -->
    {% for post in posts %}
      <div class="post-block">
        {% include "_post.html"%}
        <br>
        <p style="display:inline">Post in group: <a href="{% url 'groups:detail' slug=post.group.slug %}">{{post.group}}</a></p>
        <p style="display:inline; float:right">Date: {{post.date_posted}}</p>
      </div>
      <br>
    {% endfor %}
  {% endif %}
</div>
<br><br>

{% endif %}
{% endblock %}

punk_social/accounts/templates/register.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Registration page -->

<div class="container filled">
  <div class="row">
    <div class="container">
      <h2 class="card-title text-center"><b>Sign Up!</b></h2>
      <form class="" method="POST">
        <!-- Sign up form -->
        {% csrf_token %}
        <fieldset class="form-group">
          <br/>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button
          class="btn btn-lg btn-primary btn-block text-uppercase"
          type="submit"
          >
          Sign Up</button>
          <br/><br/>
        </div>

        <small>
          <p class="text-center">
            Already Registered!
          <a href="{% url 'accounts:login' %}"><b>Login Now!</b></a>
          </p>
        </small>
      </form>
    </div>
  </div>
</div>
<br><br>

{% endblock %}