punk_social/accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from accounts import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

### Accounts URLs ###
# Password reset still in development 

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^signup/$', user_views.register, name='register'),
    url('^profile/(?P<slug>[-\w]+)/$', user_views.profile_view, name='profile_view'),
    url('^edit-profile/$', user_views.edit_profile, name='edit_profile'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    url(r'^password-reset/done/', auth_views.PasswordResetView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

punk_social/groups/urls.py
from django.conf.urls import url
from . import views

### Group URLs ###

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(template_name='group_list.html'),name='list'),
    url(r'^new/$',views.CreateGroup.as_view(template_name='group_form.html'),name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/$',views.GroupDetail.as_view(template_name='group_detail.html'),name='detail'),
    url(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
    url(r'^delete/(?P<slug>[-\w]+)/$',views.DeleteGroup.as_view(template_name='group_confirm_delete.html'),name='delete'),
    url(r'^edit/(?P<slug>[-\w]+)/$',views.GroupUpdateView.as_view(template_name='group_update_form.html'),name='edit_group'),
]

punk_social/posts/urls.py
from django.conf.urls import url
from . import views

### Posts URLs ###

app_name = 'posts'

urlpatterns = [
    url(r'^new/$',views.CreatePost.as_view(template_name='post_form.html'),name='create'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.post_detail,name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(template_name='post_confirm_delete.html'),name='delete'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
]

punk_social/punk_social/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views
from accounts import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

punk_social/groups/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils import timezone
# link embedding, markdown inside of posts
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

### Groups models ###

# Group model
class Group(models.Model):
    # unique name and slug that don't overlap
    created_by = models.ForeignKey(User, related_name='groups_created')
    name = models.CharField(max_length=128,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    # For html of group description with misaka
    description_html = models.TextField(editable=False,default='',blank=True)
    # members belonging to group
    members = models.ManyToManyField(User,through='GroupMember')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:detail',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

# Membership model relating user to groups
class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships')
    user = models.ForeignKey(User, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

# Groups models

punk_social/groups/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Group

### Group forms ###

class GroupUpdateForm(forms.ModelForm):

	class Meta:
		model = Group
		fields = ['name', 'description']

punk_social/groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.shortcuts import get_object_or_404

from groups.models import Group,GroupMember
from . import models
from .forms import GroupUpdateForm

from django.views import generic

### Group Views ###

# Create group uses generic CreateView
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    # fields able to create
    fields = ['name','description']
    model = Group

    # Sets group description as required
    def get_form(self, form_class=None):
        form = super(CreateGroup, self).get_form(form_class)
        form.fields['description'].required = True
        return form

    # Adds author to list of group members
    def form_valid(self,form):
        form.instance.created_by = self.request.user
        result = super().form_valid(form)
        GroupMember.objects.create(user=self.request.user, group=self.object)
        return result

# Group detail uses generic DetailView
class GroupDetail(generic.DetailView):
    model = Group

# Group list uses generic ListView
class ListGroups(generic.ListView):
    model = Group

    # Add the list of joined groups for user to context dict
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_groups = Group.objects.filter(members=self.request.user)
        context['user_groups'] = user_groups
        return context

# Join group view uses generic RedirectView
class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail',kwargs={'slug':self.kwargs.get('slug')})

    # Get group object and add user as member following try/except
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except:
            messages.warning(self.request,'Warning, already a member!')
        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)

# Leave group uses generic RedirectView
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:detail',kwargs={'slug':self.kwargs.get('slug')})

    # Get group object and remove user as member following try/except
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not a member in this group')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')

        return super().get(request,*args,**kwargs)

# Delete group uses generic DeleteView following confirmation by form
class DeleteGroup(LoginRequiredMixin,generic.DeleteView):
    model = models.Group

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Group Deleted!')
        return super().delete(*args)

    def get_success_url(self):
        return reverse_lazy('groups:list')

# Group update uses generic UpdateView
class GroupUpdateView(generic.UpdateView):
    model = models.Group
    fields = ['name','description']

punk_social/groups/templates/group_confirm_delete.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Group confirm delete -->

<div class="jumbotron">
  <form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete "{{object}}" ?</h2>
    <input type="submit" name="" value="Confirm" class="btn btn-danger">
  </form>
</div>

{% endblock %}

punk_social/groups/templates/group_detail.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Group detail page -->

<div class="row">
  <div class="col-lg-12">
    <!-- Page header -->
    <div class="content-block filled page-header">
      <h1>Group: {{group.name}}</h1>
      <h4>Member Count: {{group.members.count}}</h4>
      <h5>Author: <a href="{% url 'accounts:profile_view' slug=group.created_by.profile.slug %}">{{group.created_by}}</a></h5>

      <div class="content">
        <!-- If user is inside list of members show create post or leave group -->
        {% if user in group.members.all %}
          <a href="{% url 'posts:create' %}"
            class="btn btn-fill btn-info btn-sm chill"><span
            class="glyphicon glyphicon-ok-circle"></span> Create Post</a>

          <a href="{% url 'groups:leave' slug=group.slug %}"
            class="btn btn-fill btn-warning btn-sm chill"><span
            class="glyphicon glyphicon-remove-circle"></span> Leave</a>
        <!-- Otherwise show join group option -->
        {% else %}
          <a href="{% url 'groups:join' slug=group.slug %}"
            class="btn btn-fill btn-default btn-sm chill"><span
            class="glyphicon glyphicon-ok-circle"></span> Join</a>
        {% endif %}
        <!-- If user is author show delete group option -->
        {% if request.user == group.created_by %}
          <a href="{% url 'groups:delete' slug=group.slug %}"
            class="btn btn-fill btn-danger btn-sm chill"><span
            class="glyphicon glyphicon-remove-circle"></span> Delete</a>
        {% endif %}
      </div>
      <br>
    </div>
  </div>
</div>

<div class="row">
  <!-- Group info left col -->
  <div class="col-md-4">
    <div class="clear group-description">
      <h2>Group info:</h2>
      <h6>Description: {{group.description_html|safe}}</h6>
      <h6>Number of posts: {{group.posts.count}}</h6>
      <h6>Date created: {{group.created_at}}</h6>
    </div>
  </div>
  <!-- Post list right col -->
  <div class="col-md-8">
    <div class="clear">
      <h2 class="sans-font">Posts:</h2>
      <!-- Check if there are existing posts then list them -->
      {% if group.posts.count == 0 %}
        <h2 class="">No posts in this group yet!</h2>
      {% else %}
        {% for post in group.posts.all %}
        <div class="post-block">
          {% include "_post.html"%}
          <br>
          <p style="display:inline; float:right">Date: {{post.date_posted}}</p>
          <br>
        </div>
        <br>
        {% endfor %}
      {% endif %}
    </div>
  </div>
</div>
<br><br>

{% endblock %}

punk_social/groups/templates/group_form.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Group creation form -->
<div class="container filled">
  <h4 class="text-center">Create a new Group!</h4>
  <fieldset class="form-group">
    <form action="{% url 'groups:create' %}" method="post" id="groupform">
      {% csrf_token %}
      <!-- Group create form -->
      {{ form|crispy }}
      <input type="submit" class="btn btn-primary btn-large" value="Create">
    </form>
  </fieldset>
</div>
<br><br>

{% endblock %}

punk_social/groups/templates/group_list.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}

{% block bodyblock %}
{% if user.is_authenticated %}

<!-- Group list page -->

<!-- Page header -->
<div class="row">
  <div class="col-lg-12 filled page-header">
    <h1>Welcome to the Groups Page!</h1>
    <h4 style="display:inline; float:left;">Create or join chat groups</h4>
    <h5 style="display:inline; float:right;">Number of groups:
      <span class="badge">{{object_list.count}}</span>
    </h5>
    <br>
  </div>
</div>
<br>

<!-- Groups list content -->
<div class="row">
  <!-- User Groups -->
  <div class="col-md-4">
    <div class="filled content-block user-groups">
      <h4 class="text-center" style="margin:5px">@{{user.username}}'s Groups:</h4>
      <br>
      <a href="{% url 'groups:create' %}" class="btn btn-sm btn-block btn-primary">
        <span class="glyphicon glyphicon-plus-sign"></span>
        Create New Group
      </a>
      <br>

      <!-- Created Groups -->
      <h5 class="text-center" style="margin:5px">Created groups:</h5>
      <!-- Loop all created groups from user model related_name -->
      {% for group in user.groups_created.all %}
        <div class="group-thumbnail">
          <p>
            <a href="{% url 'groups:detail' slug=group.slug %}">{{group.name}}</a>
            <br>
            <strong>{{group.members.count}}</strong>
            Member{{group.members.count|pluralize}} |
            <strong>{{group.posts.count}}</strong>
            Post{{group.posts.count|pluralize}}
          </p>
        </div>
        <br>
      {% endfor %}

      <!-- Joined Groups -->
      <h5 class="text-center" style="margin:5px">Joined Groups:</h5>
      <!-- Loop all groups filtered by membership and fed in from context dict -->
      {% for group in user_groups %}
        <div class="group-thumbnail">
          <p>
            <a href="{% url 'groups:detail' slug=group.slug %}">{{group.name}}</a>
            <br>
            <strong>{{group.members.count}}</strong>
            Member{{group.members.count|pluralize}} |
            <strong>{{group.posts.count}}</strong>
            Post{{group.posts.count|pluralize}}
          </p>
        </div>
        <br>
      {% endfor %}
      <br>
    </div>
  </div>

  <!-- All groups list -->
  <div class="col-md-8 clear">
    <h3>Groups:</h3>
    <!-- Loop through all existing groups -->
    {% for group in object_list %}
    <a href="{% url 'groups:detail' slug=group.slug %}" class="list-group-item">
      <h3 class="title list-group-item-heading">{{group.name}}</h3>
      <div class="list-group-item-text container-fluid group-description">
        {{group.description_html|safe}}
        <div class="row">
          <div class="col-md-4">
            <span class="badge">{{group.members.count}}</span>
            Member{{group.members.count|pluralize}}
            <span class="badge">{{group.posts.count}}</span>
            Post{{group.posts.count|pluralize}}
          </div>
          <div class="col-md-8">
            <h6 style="text-align:right">Date created: {{group.created_at}}</h6>
          </div>
        </div>
      </div>
    </a>
    <!-- If user is author show group edit option -->
    {% if group in user.groups_created.all %}
      <a href="{% url 'groups:edit_group' slug=group.slug %}" class="btn btn-primary btn-sm" style="float:right;">Edit Group</a>
      <br>
    {% endif %}
    <br>
    {% endfor %}
  </div>
</div>
{% endif %}
<br><br>

{% endblock %}

punk_social/groups/templates/group_update_form.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Group update page -->

<div class="container filled">
  <div class="row">
    <div class="col-lg-12 mx-auto">
      <h5 class="text-center"><b>Update Group</b></h5>
      <!-- Group update form -->
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <br>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button
            class="btn btn-primary btn-block text-uppercase"
            type="submit"
          >
          Update</button>
          <br>
          <a
            class="btn btn-warning btn-block text-uppercase"
            href="#"
            >Go Back</a
            >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}