punk_social/accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from accounts import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

### Accounts URLs ###
# Password reset still in development 

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^signup/$', user_views.register, name='register'),
    url('^profile/(?P<slug>[-\w]+)/$', user_views.profile_view, name='profile_view'),
    url('^edit-profile/$', user_views.edit_profile, name='edit_profile'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    url(r'^password-reset/done/', auth_views.PasswordResetView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

punk_social/groups/urls.py
from django.conf.urls import url
from . import views

### Group URLs ###

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(template_name='group_list.html'),name='list'),
    url(r'^new/$',views.CreateGroup.as_view(template_name='group_form.html'),name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/$',views.GroupDetail.as_view(template_name='group_detail.html'),name='detail'),
    url(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
    url(r'^delete/(?P<slug>[-\w]+)/$',views.DeleteGroup.as_view(template_name='group_confirm_delete.html'),name='delete'),
    url(r'^edit/(?P<slug>[-\w]+)/$',views.GroupUpdateView.as_view(template_name='group_update_form.html'),name='edit_group'),
]

punk_social/posts/urls.py
from django.conf.urls import url
from . import views

### Posts URLs ###

app_name = 'posts'

urlpatterns = [
    url(r'^new/$',views.CreatePost.as_view(template_name='post_form.html'),name='create'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.post_detail,name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(template_name='post_confirm_delete.html'),name='delete'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
]

punk_social/punk_social/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views
from accounts import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

punk_social/templates/about.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- About page for Punk Social -->

<!-- Welcome header with login and signup option  -->
<div class="jumbotron">
  <div class="container">
    <h1 class="sans-font">About Punk Social!</h1>
    <p class="">Punk Social is a simple social site used as a CRUD project
      demonstration. The idea is to create groups within Punk Social, join groups,
      and post within these groups with relevant information. One can only post
      in a group that they belong to. Although this is true, all groups are public
      and all posts made by a user can be seen on their profile page. The profile
      also displays groups that the user has authored and joined. Only the group
      author can delete a group. Likewise, only a post or comment author can delete
      their own content.
    </p>
    <p class="">
      This project uses the Django user model and couples a separate created model
      which allows the user to customize their profile including a profile picture,
      user bio, and portfolio site link. Both generic class based views and custom
      function views are used. Models are built using SQLite and views display
      SQLite query skills. This project also uses features such as Bootstrap
      integration, template inheritance, permissions based views, relative URL
      linking, and custom form validation.
    </p>
    <h5 class="">Thank you for your visit!</h5>
  </div>
</div>


{% endblock %}

punk_social/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">

<!-- Base HTML template for Punk Social project -->

<head>
  <meta charset="utf-8">
  <title>Punk Social!</title>

  <!-- Bootstrap links -->
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- Google font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@1&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Montserrat&display=swap" rel="stylesheet">

  <!-- Master Css -->
  <link rel="stylesheet" href="{% static 'css/master.css' %}">

  <!-- Background image -->
  <style>
    body {
      background: url({% static 'images/concrete.jpg'%}) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz--background-size: cover;
      -o--background-size: cover;
      background-size: cover;
    }""
  </style>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-default mynav" role="navigation" id="navbar">
    <div class="container">
      <a class="navbar-brand indie-font" href="{% url 'home' %}"><strong>Punk Social</strong></a>
      <ul class="nav navbar-nav navbar-right">
        <!-- Show navbar options relative to user login status -->
        {% if user.is_authenticated %}
        <li><a href="{% url 'posts:create' %}">Post</a></li>
        <li><a href="{% url 'groups:list' %}">Groups</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li>
          <!-- Corner profile picture -->
          <a href="{% url 'accounts:profile_view' slug=user.profile.slug %}">
            <div class="text-center profile-corner" style="">
              <img src="{{user.profile.image.url}}" alt="" style="max-width:100%;" >
            </div>
          </a>
        </li>
        {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
        <li><a href="{% url 'accounts:register' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container body-block">
    {% block bodyblock %}

    {% endblock %}
  </div>

  <!-- Static footer for background credits -->
  <div class="footer">
    <small>
      Page created by Daniel Sales as Django Demo Project!
      <!-- Concrete (concrete.jpg) -->
      <a href="https://www.freepik.com/free-photo/solid-concrete-wall-textured-backdrop_17839221.htm#query=black%20background&position=0&from_view=keyword">Image by rawpixel.com</a> on Freepik
      <!-- Pattern (dark.jpg) -->
      <!-- <a href="https://www.freepik.com/free-vector/floral-ornamental-abstract-background_6189902.htm#query=black%20background&position=1&from_view=keyword">Image by pikisuperstar</a> on Freepik -->
    </small>
  </div>
</body>

</html>

punk_social/templates/home.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Home page for Punk Social -->

<!-- Welcome header with login and signup option  -->
<div class="jumbotron">
  <div class="container">
    <h1 class="sans-font">Welcome to Punk Social!</h1>
    {% if not user.is_authenticated %}
      <h4>Please <a href="{% url 'accounts:login' %}">Login</a> or
        <a href="{% url 'accounts:register' %}">Sign up!</a>
      </h4>
    {% endif %}
  </div>
</div>

<!-- List of all groups if user is logged in -->
{% if user.is_authenticated %}
<div class="clear">
  <h3>Groups:</h3>
  {% for group in object_list %}
  <a href="{% url 'groups:detail' slug=group.slug %}" class="list-group-item">
    <h3 class="title list-group-item-heading">{{group.name}}</h3>
    <div class="list-group-item-text container-fluid group-description" >
      <p>{{group.description_html|safe}}</p>
      <div class="row">
        <div class="col-md-4">
          <span class="badge">{{group.members.count}}</span>
          Member{{group.members.count|pluralize}}
          <span class="badge">{{group.posts.count}}</span>
          Post{{group.posts.count|pluralize}}
        </div>
      </div>
    </div>
  </a>
  <!-- If user is group author show delete option -->
  {% if group in user.groups_created.all %}
    <a href="{% url 'groups:edit_group' slug=group.slug %}" class="btn btn-primary btn-sm" style="float:right;">Edit Group</a>
    <br>
  {% endif %}
  <br>
  {% endfor %}
</div>
{% endif %}
<br><br>

{% endblock %}