punk_social/accounts/urls.py
from django.contrib import admin
from django.conf.urls import url
from accounts import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

### Accounts URLs ###
# Password reset still in development 

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^signup/$', user_views.register, name='register'),
    url('^profile/(?P<slug>[-\w]+)/$', user_views.profile_view, name='profile_view'),
    url('^edit-profile/$', user_views.edit_profile, name='edit_profile'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    url(r'^password-reset/done/', auth_views.PasswordResetView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

punk_social/posts/urls.py
from django.conf.urls import url
from . import views

### Posts URLs ###

app_name = 'posts'

urlpatterns = [
    url(r'^new/$',views.CreatePost.as_view(template_name='post_form.html'),name='create'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.post_detail,name='detail'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(template_name='post_confirm_delete.html'),name='delete'),
    url(r'^comment/(?P<pk>\d+)/remove/$',views.comment_remove,name='comment_remove'),
]

punk_social/punk_social/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views
from accounts import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

punk_social/posts/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
import misaka

from groups.models import Group

# Connect post to current user
User = get_user_model()

### Post models ###

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts', on_delete=models.CASCADE)
    content = models.TextField()
    content_html = models.TextField(editable=False)
    date_posted = models.DateTimeField(default=timezone.now)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.content

    def save(self,*args,**kwargs):
        self.content_html = misaka.html(self.content)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:detail',kwargs={'username':self.user.username,
                                                'pk':self.pk})

    class Meta:
        # Ordered by descending time posted
        ordering = ['-date_posted']
        # Every message uniquely linked to a user
        unique_together = ['user','content']


class Comments(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    username = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    comment = models.TextField()
    comment_html = models.TextField(editable=False)
    comment_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

    def save(self,*args,**kwargs):
        self.comment_html = misaka.html(self.comment)
        super().save(*args,**kwargs)

# Like use still in development
class Like(models.Model):
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)

punk_social/posts/forms.py
from django import forms
from .models import Comments

### Post forms ###

class NewCommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ['comment']

punk_social/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views import generic
from django.shortcuts import get_object_or_404, render, redirect

from . import models
from groups.models import Group
from .forms import NewCommentForm

from braces.views import SelectRelatedMixin

from django.contrib.auth import get_user_model
User = get_user_model()

### Posts views ###

# Create post uses generic CreateView
class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ['content','group']
    model = models.Post

    # Filter so user can only post in group with membership
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.group_choices = Group.objects.filter(members = self.request.user)
        context['form'].fields['group'].queryset = self.group_choices
        return context

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

# Post detail view built with function view to implement likes
# Like post still in development
@login_required
def post_detail(request, username, pk):
    post = get_object_or_404(models.Post, pk=pk)
    user = request.user
    is_liked =  models.Like.objects.filter(user=user, post=post)
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.post = post
            data.username = user
            data.save()
            return redirect('posts:detail', username=username, pk=pk)
    else:
        form = NewCommentForm()
    return render(request, 'post_detail.html', {'post':post, 'is_liked':is_liked, 'form':form})

# Post detail view built with generic DetailView
# NOT in use currently
class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        # Get query set for post and filter where username matches
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

# Post delete uses generic DeleteView
class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted!')
        return super().delete(*args)

    def get_success_url(self):
        return reverse_lazy('accounts:profile_view', kwargs={'slug':self.request.user.profile.slug})

# Remove comment
@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(models.Comments,pk=pk)
    # Save pk before delete so it can still be referenced
    username = comment.post.user.profile.slug
    post_pk = comment.post.pk
    comment.delete()
    return redirect('posts:detail',pk=post_pk, username=username)

punk_social/posts/templates/_post.html
<!-- HTML code for individual posts to inject into post views -->

<!-- Post content from model -->
<div class="post-content">
  <a href="{% url 'posts:detail' username=post.user.username pk=post.pk %}"
    class="">
    <h4 class="">{{post.content_html|safe}}</h4>
  </a>
</div>

<!-- Post footer -->
<h5 class="media-footer" style="padding-top:0px; padding-left:10px; margin-bottom:0px;">
  <span class="username">
    <!-- Username is profile link -->
    <a class="" href="{% url 'accounts:profile_view' slug=post.user.profile.slug %}"><strong>@{{post.user.username}}</strong></a>
  </span>
  <time class="time" style="padding-left:10px">
    {{post.created_at}}
  </time>

  <!-- If user is post author show delete option -->
  {% if user.is_authenticated and post.user == user %}
  <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-default btn-xs pull-right">
    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
    <span class="text-danger icon-label">Delete</span>
  </a>
  {% endif %}
</h5>

punk_social/posts/templates/post_confirm_delete.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Post confirm delete page -->

<div class="jumbotron">
  <!-- Confirm delete form -->
  <form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete this post:</h2>
    <h5>{{object.content_html|safe}}</h5>
    <input type="submit" name="" value="Confirm" class="btn btn-danger">
  </form>
</div>
<br><br>

{% endblock %}

punk_social/posts/templates/post_detail.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Post detail page -->

<!-- Page header -->
<div class="row">
  <div class="col-lg-12 page-header filled">
  <h2>Post in group:
    <a href="{% url 'groups:detail' slug=post.group.slug %}">{{post.group.name}}</a>
  </h2>
  <h4>Number of comments: {{post.comments.count}}</h4>
  <h5>Author: <a href="{% url 'accounts:profile_view' slug=post.user.profile.slug %}">
    {{post.user.username}}</a>
  </h5>
  </div>
</div>
<br>

<!-- Post content and comment string -->
<div class="row">
  <!-- Post content -->
  <div class="col-md-8">
    <!-- Include post -->
    <div class="post-block">
      {% include "_post.html" %}
    </div>
    <br>

    <!-- Comments -->
    <div class="clear">
      <h4 class="sans-font"><strong>Comments:</strong></h4>
      <!-- Check for existing comments and loop through them -->
      {% if post.comments.count == 0 %}
        <h5>No comments yet!</h5>
      {% else %}
        {% for comment in post.comments.all %}
          <div class="clear comment">
            <div class="" style="clear: both">
            <p>
              <span style="float:left">
                <strong>@{{comment.username.username}}:</strong>
              </span>
              <span style="float:right">{{comment.comment_date}}</span>
            </p>
            </div>
            <br>
            <p>{{comment.comment_html|safe}}</p>
          </div>
          <!-- If user is comment author show delete option -->
          {% if comment in user.comments.all %}
            <a href="{% url 'posts:comment_remove' pk=comment.pk %}"
            class="btn btn-danger btn-xs" style="float:right; margin-top:5px;"
            onclick="return confirm('Are you sure you want to delete this comment?')">
              Delete
            </a>
            <br>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
  </div>

  <!-- Comment form -->

  {% if user in post.group.members.all %}
  <div class="col-md-4">
    <div class="clear">
    <form class="pop chill" action="" method="post" id="NewCommentForm">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" class="btn btn-primary btn-large" value="Comment">
    </form>
    </div>
  </div>
  {% endif %}
</div>
<br><br>

{% endblock %}

punk_social/posts/templates/post_form.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load bootstrap3 %}{% load static %}
{% block bodyblock %}

<!-- Create post form -->

<div class="container filled">
  <h4>Create a new Post</h4>
  <!-- Post form -->
  <form id="postForm" action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Post" class="btn btn-primary btn-large">
  </form>
<br>
</div>
<br><br>

{% endblock %}